[package]
name = "marvels"
version = "0.1.0"
edition = "2024"
authors = ["Paul Pacher <paul.pacher@gmail.com>"]

[dependencies]


[workspace]
members = [
    "cli",
    "client",
    "proto",
    "server"
]
